contact_links:
  - name: I have a question 🤔
    url: https://github.com/fastapi-users/fastapi-users/discussions
    about: If you have any question about the usage of FastAPI Users that's not clearly a bug, please open a discussion first.
